Repository badal-io/gcp-airflow-foundations, pull requests merged in 2021-11, with the labels that each got.

#17 Schema parsing method and DagBuilder class refactoring (AF-43)
  src/gcp_airflow_foundations/base_class/schema_options_config.py
  src/gcp_airflow_foundations/base_class/source_config.py
  src/gcp_airflow_foundations/base_class/source_table_config.py
  src/gcp_airflow_foundations/common/gcp/hds/schema_utils.py
  src/gcp_airflow_foundations/common/gcp/load_builder.py
  src/gcp_airflow_foundations/common/gcp/ods/schema_utils.py
  src/gcp_airflow_foundations/common/gcp/source_schema/bq.py
  src/gcp_airflow_foundations/common/gcp/source_schema/gcs.py
  src/gcp_airflow_foundations/enums/schema_source_type.py
  src/gcp_airflow_foundations/operators/gcp/create_table.py
  src/gcp_airflow_foundations/operators/gcp/gcs_to_bigquery.py
  src/gcp_airflow_foundations/operators/gcp/hds/hds_merge_table_operator.py
  src/gcp_airflow_foundations/operators/gcp/hds/load_hds_taskgroup.py
  src/gcp_airflow_foundations/operators/gcp/ods/load_ods_taskgroup.py
  src/gcp_airflow_foundations/operators/gcp/ods/ods_merge_table_operator.py
  src/gcp_airflow_foundations/operators/gcp/schema_migration/schema_migration_operator.py
  src/gcp_airflow_foundations/operators/gcp/schema_parsing/__init__.py
  src/gcp_airflow_foundations/operators/gcp/schema_parsing/schema_parsing_operator.py
  src/gcp_airflow_foundations/source_class/gcs_source.py
  src/gcp_airflow_foundations/source_class/schema_source_config.py
  src/gcp_airflow_foundations/source_class/source.py
Labels: kind:enhancement, area:core

#21 feature/dataflow_ingestion
  src/gcp_airflow_foundations/base_class/dataflow_job_config.py
  src/gcp_airflow_foundations/common/dataflow/__init__.py
  src/gcp_airflow_foundations/common/dataflow/jdbc/__init__.py
  src/gcp_airflow_foundations/common/dataflow/jdbc/dataflow_taskgroups.py
  src/gcp_airflow_foundations/common/dataflow/jdbc/oracle/__init__.py
  src/gcp_airflow_foundations/common/dataflow/jdbc/oracle/oracle_query_helpers.py
  src/gcp_airflow_foundations/enums/source_type.py
  src/gcp_airflow_foundations/operators/gcp/create_table.py
  src/gcp_airflow_foundations/source_class/__init__.py
  src/gcp_airflow_foundations/source_class/jdbc_dataflow_source.py
  src/gcp_airflow_foundations/source_class/oracle_dataflow_source.py
  src/gcp_airflow_foundations/source_class/source.py
Labels: kind:enhancement, area:source-operators

#14 Feature/salesforce
  src/gcp_airflow_foundations/base_class/salesforce_ingestion_config.py
  src/gcp_airflow_foundations/base_class/source_table_config.py
  src/gcp_airflow_foundations/enums/source_type.py
  src/gcp_airflow_foundations/operators/api/operators/sf_to_gcs_query_operator.py
  src/gcp_airflow_foundations/source_class/__init__.py
  src/gcp_airflow_foundations/source_class/salesforce_source.py
Labels: kind:enhancement, area:source-operators

#24 Updates to unit and integration tests
  requirements.txt
  src/gcp_airflow_foundations/operators/gcp/hds/hds_merge_table_operator.py
  src/gcp_airflow_foundations/operators/gcp/ods/ods_merge_table_operator.py
  src/gcp_airflow_foundations/operators/gcp/schema_migration/schema_migration_operator.py
  tests/integration/test_hds_scd2.py
  tests/integration/test_hds_snapshot.py
  tests/integration/test_ods.py
  tests/integration/test_twilio_api_connection.py
  tests/unit/test_schema_migration_operator.py
  tests/unit/test_schema_parsing.py
  tests/unit/test_sql_generation.py
  tests/unit/test_task_group_builders.py
Labels: area:testing

#26 Enable optional separate ODS and HDS datasets
  src/gcp_airflow_foundations/base_class/source_config.py
  src/gcp_airflow_foundations/common/gcp/load_builder.py
Labels: kind:enhancement, area:core

#31 Hothix: ODS and HDS column mapping error when null
  src/gcp_airflow_foundations/common/gcp/load_builder.py
  src/gcp_airflow_foundations/operators/gcp/hds/hds_merge_table_operator.py
  src/gcp_airflow_foundations/operators/gcp/ods/ods_merge_table_operator.py
Labels: kind:bug

#32 Hotfix to enable source discovery for external sources (AF-11)
  src/gcp_airflow_foundations/base_class/source_config.py
  src/gcp_airflow_foundations/operators/gcp/gcs_to_bigquery.py
  src/gcp_airflow_foundations/parse_dags.py
  src/gcp_airflow_foundations/source_class/gcs_source.py
  src/gcp_airflow_foundations/source_class/jdbc_dataflow_source.py
  src/gcp_airflow_foundations/source_class/salesforce_source.py
  src/gcp_airflow_foundations/source_class/source.py
Labels: kind:bug, area:core

#33 Add execution date to staging table id
  requirements.txt
  src/gcp_airflow_foundations/common/gcp/load_builder.py
  src/gcp_airflow_foundations/operators/gcp/create_table.py
  src/gcp_airflow_foundations/operators/gcp/delete_staging_table.py
  src/gcp_airflow_foundations/operators/gcp/ods/ods_merge_table_operator.py
  src/gcp_airflow_foundations/operators/gcp/schema_parsing/schema_parsing_operator.py
  src/gcp_airflow_foundations/source_class/schema_source_config.py
Labels: kind:bug, area:core

#34 dataform-operator-COG-92
  src/gcp_airflow_foundations/operators/api/hooks/dataform_hook.py
  src/gcp_airflow_foundations/operators/api/operators/dataform_operator.py
Labels: kind:enhancement, area:source-operators

#37 Added job location for the BigQuery operator
  src/gcp_airflow_foundations/base_class/source_config.py
  src/gcp_airflow_foundations/common/gcp/load_builder.py
  src/gcp_airflow_foundations/operators/gcp/hds/hds_merge_table_operator.py
  src/gcp_airflow_foundations/operators/gcp/hds/load_hds_taskgroup.py
  src/gcp_airflow_foundations/operators/gcp/ods/load_ods_taskgroup.py
  src/gcp_airflow_foundations/operators/gcp/ods/ods_merge_table_operator.py
Labels: kind:enhancement, area:source-operators

#38 Fixed ODS/HDS table name to be taken from the landing_zone_table_name…
  src/gcp_airflow_foundations/common/gcp/load_builder.py
Labels: kind:bug, area:core

#39 HDS Snapshot was changed to use the execution time
  src/gcp_airflow_foundations/operators/gcp/hds/hds_merge_table_operator.py
  src/gcp_airflow_foundations/operators/gcp/hds/hds_sql_upsert_helpers.py
Labels: kind:bug, area:source-operators
